"""World regions mapping data - Countries with their states/provinces."""

# Country data with ISO codes
COUNTRIES = {
    "United States": {"code": "US", "iso2": "us", "capital": "Washington, D.C."},
    "India": {"code": "IN", "iso2": "in", "capital": "New Delhi"},
    "China": {"code": "CN", "iso2": "cn", "capital": "Beijing"},
    "Brazil": {"code": "BR", "iso2": "br", "capital": "Brasília"},
    "Russia": {"code": "RU", "iso2": "ru", "capital": "Moscow"},
    "Canada": {"code": "CA", "iso2": "ca", "capital": "Ottawa"},
    "Australia": {"code": "AU", "iso2": "au", "capital": "Canberra"},
    "Germany": {"code": "DE", "iso2": "de", "capital": "Berlin"},
    "France": {"code": "FR", "iso2": "fr", "capital": "Paris"},
    "United Kingdom": {"code": "GB", "iso2": "gb", "capital": "London"},
    "Japan": {"code": "JP", "iso2": "jp", "capital": "Tokyo"},
    "Mexico": {"code": "MX", "iso2": "mx", "capital": "Mexico City"},
    "Italy": {"code": "IT", "iso2": "it", "capital": "Rome"},
    "Spain": {"code": "ES", "iso2": "es", "capital": "Madrid"},
    "South Korea": {"code": "KR", "iso2": "kr", "capital": "Seoul"},
    "Indonesia": {"code": "ID", "iso2": "id", "capital": "Jakarta"},
    "Turkey": {"code": "TR", "iso2": "tr", "capital": "Ankara"},
    "Saudi Arabia": {"code": "SA", "iso2": "sa", "capital": "Riyadh"},
    "Argentina": {"code": "AR", "iso2": "ar", "capital": "Buenos Aires"},
    "South Africa": {"code": "ZA", "iso2": "za", "capital": "Pretoria"},
    "Nigeria": {"code": "NG", "iso2": "ng", "capital": "Abuja"},
    "Egypt": {"code": "EG", "iso2": "eg", "capital": "Cairo"},
    "Pakistan": {"code": "PK", "iso2": "pk", "capital": "Islamabad"},
    "Thailand": {"code": "TH", "iso2": "th", "capital": "Bangkok"},
    "Poland": {"code": "PL", "iso2": "pl", "capital": "Warsaw"},
    "Netherlands": {"code": "NL", "iso2": "nl", "capital": "Amsterdam"},
    "Switzerland": {"code": "CH", "iso2": "ch", "capital": "Bern"},
    "Sweden": {"code": "SE", "iso2": "se", "capital": "Stockholm"},
    "Norway": {"code": "NO", "iso2": "no", "capital": "Oslo"},
}

# States/Provinces for each country
REGIONS = {
    "United States": {
        "Alabama": {"code": "AL", "capital": "Montgomery"},
        "Alaska": {"code": "AK", "capital": "Juneau"},
        "Arizona": {"code": "AZ", "capital": "Phoenix"},
        "Arkansas": {"code": "AR", "capital": "Little Rock"},
        "California": {"code": "CA", "capital": "Sacramento"},
        "Colorado": {"code": "CO", "capital": "Denver"},
        "Connecticut": {"code": "CT", "capital": "Hartford"},
        "Delaware": {"code": "DE", "capital": "Dover"},
        "Florida": {"code": "FL", "capital": "Tallahassee"},
        "Georgia": {"code": "GA", "capital": "Atlanta"},
        "Hawaii": {"code": "HI", "capital": "Honolulu"},
        "Idaho": {"code": "ID", "capital": "Boise"},
        "Illinois": {"code": "IL", "capital": "Springfield"},
        "Indiana": {"code": "IN", "capital": "Indianapolis"},
        "Iowa": {"code": "IA", "capital": "Des Moines"},
        "Kansas": {"code": "KS", "capital": "Topeka"},
        "Kentucky": {"code": "KY", "capital": "Frankfort"},
        "Louisiana": {"code": "LA", "capital": "Baton Rouge"},
        "Maine": {"code": "ME", "capital": "Augusta"},
        "Maryland": {"code": "MD", "capital": "Annapolis"},
        "Massachusetts": {"code": "MA", "capital": "Boston"},
        "Michigan": {"code": "MI", "capital": "Lansing"},
        "Minnesota": {"code": "MN", "capital": "Saint Paul"},
        "Mississippi": {"code": "MS", "capital": "Jackson"},
        "Missouri": {"code": "MO", "capital": "Jefferson City"},
        "Montana": {"code": "MT", "capital": "Helena"},
        "Nebraska": {"code": "NE", "capital": "Lincoln"},
        "Nevada": {"code": "NV", "capital": "Carson City"},
        "New Hampshire": {"code": "NH", "capital": "Concord"},
        "New Jersey": {"code": "NJ", "capital": "Trenton"},
        "New Mexico": {"code": "NM", "capital": "Santa Fe"},
        "New York": {"code": "NY", "capital": "Albany"},
        "North Carolina": {"code": "NC", "capital": "Raleigh"},
        "North Dakota": {"code": "ND", "capital": "Bismarck"},
        "Ohio": {"code": "OH", "capital": "Columbus"},
        "Oklahoma": {"code": "OK", "capital": "Oklahoma City"},
        "Oregon": {"code": "OR", "capital": "Salem"},
        "Pennsylvania": {"code": "PA", "capital": "Harrisburg"},
        "Rhode Island": {"code": "RI", "capital": "Providence"},
        "South Carolina": {"code": "SC", "capital": "Columbia"},
        "South Dakota": {"code": "SD", "capital": "Pierre"},
        "Tennessee": {"code": "TN", "capital": "Nashville"},
        "Texas": {"code": "TX", "capital": "Austin"},
        "Utah": {"code": "UT", "capital": "Salt Lake City"},
        "Vermont": {"code": "VT", "capital": "Montpelier"},
        "Virginia": {"code": "VA", "capital": "Richmond"},
        "Washington": {"code": "WA", "capital": "Olympia"},
        "West Virginia": {"code": "WV", "capital": "Charleston"},
        "Wisconsin": {"code": "WI", "capital": "Madison"},
        "Wyoming": {"code": "WY", "capital": "Cheyenne"},
        "District of Columbia": {"code": "DC", "capital": "Washington"},
    },
    
    "India": {
        "Andhra Pradesh": {"code": "AP", "capital": "Amaravati"},
        "Arunachal Pradesh": {"code": "AR", "capital": "Itanagar"},
        "Assam": {"code": "AS", "capital": "Dispur"},
        "Bihar": {"code": "BR", "capital": "Patna"},
        "Chhattisgarh": {"code": "CG", "capital": "Raipur"},
        "Goa": {"code": "GA", "capital": "Panaji"},
        "Gujarat": {"code": "GJ", "capital": "Gandhinagar"},
        "Haryana": {"code": "HR", "capital": "Chandigarh"},
        "Himachal Pradesh": {"code": "HP", "capital": "Shimla"},
        "Jharkhand": {"code": "JH", "capital": "Ranchi"},
        "Karnataka": {"code": "KA", "capital": "Bengaluru"},
        "Kerala": {"code": "KL", "capital": "Thiruvananthapuram"},
        "Madhya Pradesh": {"code": "MP", "capital": "Bhopal"},
        "Maharashtra": {"code": "MH", "capital": "Mumbai"},
        "Manipur": {"code": "MN", "capital": "Imphal"},
        "Meghalaya": {"code": "ML", "capital": "Shillong"},
        "Mizoram": {"code": "MZ", "capital": "Aizawl"},
        "Nagaland": {"code": "NL", "capital": "Kohima"},
        "Odisha": {"code": "OD", "capital": "Bhubaneswar"},
        "Punjab": {"code": "PB", "capital": "Chandigarh"},
        "Rajasthan": {"code": "RJ", "capital": "Jaipur"},
        "Sikkim": {"code": "SK", "capital": "Gangtok"},
        "Tamil Nadu": {"code": "TN", "capital": "Chennai"},
        "Telangana": {"code": "TS", "capital": "Hyderabad"},
        "Tripura": {"code": "TR", "capital": "Agartala"},
        "Uttar Pradesh": {"code": "UP", "capital": "Lucknow"},
        "Uttarakhand": {"code": "UK", "capital": "Dehradun"},
        "West Bengal": {"code": "WB", "capital": "Kolkata"},
        "Delhi": {"code": "DL", "capital": "New Delhi"},
        "Jammu and Kashmir": {"code": "JK", "capital": "Srinagar"},
        "Ladakh": {"code": "LA", "capital": "Leh"},
    },
    
    "China": {
        "Beijing": {"code": "BJ", "capital": "Beijing"},
        "Shanghai": {"code": "SH", "capital": "Shanghai"},
        "Tianjin": {"code": "TJ", "capital": "Tianjin"},
        "Chongqing": {"code": "CQ", "capital": "Chongqing"},
        "Guangdong": {"code": "GD", "capital": "Guangzhou"},
        "Shandong": {"code": "SD", "capital": "Jinan"},
        "Henan": {"code": "HA", "capital": "Zhengzhou"},
        "Sichuan": {"code": "SC", "capital": "Chengdu"},
        "Jiangsu": {"code": "JS", "capital": "Nanjing"},
        "Hebei": {"code": "HE", "capital": "Shijiazhuang"},
        "Hunan": {"code": "HN", "capital": "Changsha"},
        "Zhejiang": {"code": "ZJ", "capital": "Hangzhou"},
        "Anhui": {"code": "AH", "capital": "Hefei"},
        "Hubei": {"code": "HB", "capital": "Wuhan"},
        "Guangxi": {"code": "GX", "capital": "Nanning"},
        "Yunnan": {"code": "YN", "capital": "Kunming"},
        "Jiangxi": {"code": "JX", "capital": "Nanchang"},
        "Liaoning": {"code": "LN", "capital": "Shenyang"},
        "Fujian": {"code": "FJ", "capital": "Fuzhou"},
        "Shaanxi": {"code": "SN", "capital": "Xi'an"},
        "Shanxi": {"code": "SX", "capital": "Taiyuan"},
        "Guizhou": {"code": "GZ", "capital": "Guiyang"},
        "Heilongjiang": {"code": "HL", "capital": "Harbin"},
        "Jilin": {"code": "JL", "capital": "Changchun"},
        "Gansu": {"code": "GS", "capital": "Lanzhou"},
        "Inner Mongolia": {"code": "NM", "capital": "Hohhot"},
        "Xinjiang": {"code": "XJ", "capital": "Urumqi"},
        "Tibet": {"code": "XZ", "capital": "Lhasa"},
        "Hong Kong": {"code": "HK", "capital": "Hong Kong"},
        "Macau": {"code": "MO", "capital": "Macau"},
        "Taiwan": {"code": "TW", "capital": "Taipei"},
    },
    
    "Brazil": {
        "Acre": {"code": "AC", "capital": "Rio Branco"},
        "Alagoas": {"code": "AL", "capital": "Maceió"},
        "Amapá": {"code": "AP", "capital": "Macapá"},
        "Amazonas": {"code": "AM", "capital": "Manaus"},
        "Bahia": {"code": "BA", "capital": "Salvador"},
        "Ceará": {"code": "CE", "capital": "Fortaleza"},
        "Distrito Federal": {"code": "DF", "capital": "Brasília"},
        "Espírito Santo": {"code": "ES", "capital": "Vitória"},
        "Goiás": {"code": "GO", "capital": "Goiânia"},
        "Maranhão": {"code": "MA", "capital": "São Luís"},
        "Mato Grosso": {"code": "MT", "capital": "Cuiabá"},
        "Mato Grosso do Sul": {"code": "MS", "capital": "Campo Grande"},
        "Minas Gerais": {"code": "MG", "capital": "Belo Horizonte"},
        "Pará": {"code": "PA", "capital": "Belém"},
        "Paraíba": {"code": "PB", "capital": "João Pessoa"},
        "Paraná": {"code": "PR", "capital": "Curitiba"},
        "Pernambuco": {"code": "PE", "capital": "Recife"},
        "Piauí": {"code": "PI", "capital": "Teresina"},
        "Rio de Janeiro": {"code": "RJ", "capital": "Rio de Janeiro"},
        "Rio Grande do Norte": {"code": "RN", "capital": "Natal"},
        "Rio Grande do Sul": {"code": "RS", "capital": "Porto Alegre"},
        "Rondônia": {"code": "RO", "capital": "Porto Velho"},
        "Roraima": {"code": "RR", "capital": "Boa Vista"},
        "Santa Catarina": {"code": "SC", "capital": "Florianópolis"},
        "São Paulo": {"code": "SP", "capital": "São Paulo"},
        "Sergipe": {"code": "SE", "capital": "Aracaju"},
        "Tocantins": {"code": "TO", "capital": "Palmas"},
    },
    
    "Canada": {
        "Alberta": {"code": "AB", "capital": "Edmonton"},
        "British Columbia": {"code": "BC", "capital": "Victoria"},
        "Manitoba": {"code": "MB", "capital": "Winnipeg"},
        "New Brunswick": {"code": "NB", "capital": "Fredericton"},
        "Newfoundland and Labrador": {"code": "NL", "capital": "St. John's"},
        "Northwest Territories": {"code": "NT", "capital": "Yellowknife"},
        "Nova Scotia": {"code": "NS", "capital": "Halifax"},
        "Nunavut": {"code": "NU", "capital": "Iqaluit"},
        "Ontario": {"code": "ON", "capital": "Toronto"},
        "Prince Edward Island": {"code": "PE", "capital": "Charlottetown"},
        "Quebec": {"code": "QC", "capital": "Quebec City"},
        "Saskatchewan": {"code": "SK", "capital": "Regina"},
        "Yukon": {"code": "YT", "capital": "Whitehorse"},
    },
    
    "Australia": {
        "New South Wales": {"code": "NSW", "capital": "Sydney"},
        "Victoria": {"code": "VIC", "capital": "Melbourne"},
        "Queensland": {"code": "QLD", "capital": "Brisbane"},
        "Western Australia": {"code": "WA", "capital": "Perth"},
        "South Australia": {"code": "SA", "capital": "Adelaide"},
        "Tasmania": {"code": "TAS", "capital": "Hobart"},
        "Northern Territory": {"code": "NT", "capital": "Darwin"},
        "Australian Capital Territory": {"code": "ACT", "capital": "Canberra"},
    },
    
    "Germany": {
        "Baden-Württemberg": {"code": "BW", "capital": "Stuttgart"},
        "Bavaria": {"code": "BY", "capital": "Munich"},
        "Berlin": {"code": "BE", "capital": "Berlin"},
        "Brandenburg": {"code": "BB", "capital": "Potsdam"},
        "Bremen": {"code": "HB", "capital": "Bremen"},
        "Hamburg": {"code": "HH", "capital": "Hamburg"},
        "Hesse": {"code": "HE", "capital": "Wiesbaden"},
        "Lower Saxony": {"code": "NI", "capital": "Hanover"},
        "Mecklenburg-Vorpommern": {"code": "MV", "capital": "Schwerin"},
        "North Rhine-Westphalia": {"code": "NW", "capital": "Düsseldorf"},
        "Rhineland-Palatinate": {"code": "RP", "capital": "Mainz"},
        "Saarland": {"code": "SL", "capital": "Saarbrücken"},
        "Saxony": {"code": "SN", "capital": "Dresden"},
        "Saxony-Anhalt": {"code": "ST", "capital": "Magdeburg"},
        "Schleswig-Holstein": {"code": "SH", "capital": "Kiel"},
        "Thuringia": {"code": "TH", "capital": "Erfurt"},
    },
    
    "France": {
        "Auvergne-Rhône-Alpes": {"code": "ARA", "capital": "Lyon"},
        "Bourgogne-Franche-Comté": {"code": "BFC", "capital": "Dijon"},
        "Brittany": {"code": "BRE", "capital": "Rennes"},
        "Centre-Val de Loire": {"code": "CVL", "capital": "Orléans"},
        "Corsica": {"code": "COR", "capital": "Ajaccio"},
        "Grand Est": {"code": "GES", "capital": "Strasbourg"},
        "Hauts-de-France": {"code": "HDF", "capital": "Lille"},
        "Île-de-France": {"code": "IDF", "capital": "Paris"},
        "Normandy": {"code": "NOR", "capital": "Rouen"},
        "Nouvelle-Aquitaine": {"code": "NAQ", "capital": "Bordeaux"},
        "Occitanie": {"code": "OCC", "capital": "Toulouse"},
        "Pays de la Loire": {"code": "PDL", "capital": "Nantes"},
        "Provence-Alpes-Côte d'Azur": {"code": "PAC", "capital": "Marseille"},
    },
    
    "United Kingdom": {
        "England": {"code": "ENG", "capital": "London"},
        "Scotland": {"code": "SCT", "capital": "Edinburgh"},
        "Wales": {"code": "WLS", "capital": "Cardiff"},
        "Northern Ireland": {"code": "NIR", "capital": "Belfast"},
        "Greater London": {"code": "LDN", "capital": "London"},
        "South East": {"code": "SE", "capital": "Guildford"},
        "South West": {"code": "SW", "capital": "Bristol"},
        "East of England": {"code": "EE", "capital": "Cambridge"},
        "West Midlands": {"code": "WM", "capital": "Birmingham"},
        "East Midlands": {"code": "EM", "capital": "Nottingham"},
        "Yorkshire": {"code": "YH", "capital": "Leeds"},
        "North West": {"code": "NW", "capital": "Manchester"},
        "North East": {"code": "NE", "capital": "Newcastle"},
    },
    
    "Japan": {
        "Hokkaido": {"code": "01", "capital": "Sapporo"},
        "Aomori": {"code": "02", "capital": "Aomori"},
        "Iwate": {"code": "03", "capital": "Morioka"},
        "Miyagi": {"code": "04", "capital": "Sendai"},
        "Akita": {"code": "05", "capital": "Akita"},
        "Yamagata": {"code": "06", "capital": "Yamagata"},
        "Fukushima": {"code": "07", "capital": "Fukushima"},
        "Ibaraki": {"code": "08", "capital": "Mito"},
        "Tochigi": {"code": "09", "capital": "Utsunomiya"},
        "Gunma": {"code": "10", "capital": "Maebashi"},
        "Saitama": {"code": "11", "capital": "Saitama"},
        "Chiba": {"code": "12", "capital": "Chiba"},
        "Tokyo": {"code": "13", "capital": "Tokyo"},
        "Kanagawa": {"code": "14", "capital": "Yokohama"},
        "Niigata": {"code": "15", "capital": "Niigata"},
        "Toyama": {"code": "16", "capital": "Toyama"},
        "Ishikawa": {"code": "17", "capital": "Kanazawa"},
        "Fukui": {"code": "18", "capital": "Fukui"},
        "Yamanashi": {"code": "19", "capital": "Kofu"},
        "Nagano": {"code": "20", "capital": "Nagano"},
        "Gifu": {"code": "21", "capital": "Gifu"},
        "Shizuoka": {"code": "22", "capital": "Shizuoka"},
        "Aichi": {"code": "23", "capital": "Nagoya"},
        "Mie": {"code": "24", "capital": "Tsu"},
        "Shiga": {"code": "25", "capital": "Otsu"},
        "Kyoto": {"code": "26", "capital": "Kyoto"},
        "Osaka": {"code": "27", "capital": "Osaka"},
        "Hyogo": {"code": "28", "capital": "Kobe"},
        "Nara": {"code": "29", "capital": "Nara"},
        "Wakayama": {"code": "30", "capital": "Wakayama"},
        "Tottori": {"code": "31", "capital": "Tottori"},
        "Shimane": {"code": "32", "capital": "Matsue"},
        "Okayama": {"code": "33", "capital": "Okayama"},
        "Hiroshima": {"code": "34", "capital": "Hiroshima"},
        "Yamaguchi": {"code": "35", "capital": "Yamaguchi"},
        "Tokushima": {"code": "36", "capital": "Tokushima"},
        "Kagawa": {"code": "37", "capital": "Takamatsu"},
        "Ehime": {"code": "38", "capital": "Matsuyama"},
        "Kochi": {"code": "39", "capital": "Kochi"},
        "Fukuoka": {"code": "40", "capital": "Fukuoka"},
        "Saga": {"code": "41", "capital": "Saga"},
        "Nagasaki": {"code": "42", "capital": "Nagasaki"},
        "Kumamoto": {"code": "43", "capital": "Kumamoto"},
        "Oita": {"code": "44", "capital": "Oita"},
        "Miyazaki": {"code": "45", "capital": "Miyazaki"},
        "Kagoshima": {"code": "46", "capital": "Kagoshima"},
        "Okinawa": {"code": "47", "capital": "Naha"},
    },
    
    "Mexico": {
        "Aguascalientes": {"code": "AGS", "capital": "Aguascalientes"},
        "Baja California": {"code": "BC", "capital": "Mexicali"},
        "Baja California Sur": {"code": "BCS", "capital": "La Paz"},
        "Campeche": {"code": "CAM", "capital": "Campeche"},
        "Chiapas": {"code": "CHP", "capital": "Tuxtla Gutiérrez"},
        "Chihuahua": {"code": "CHI", "capital": "Chihuahua"},
        "Coahuila": {"code": "COA", "capital": "Saltillo"},
        "Colima": {"code": "COL", "capital": "Colima"},
        "Durango": {"code": "DGO", "capital": "Durango"},
        "Guanajuato": {"code": "GTO", "capital": "Guanajuato"},
        "Guerrero": {"code": "GRO", "capital": "Chilpancingo"},
        "Hidalgo": {"code": "HGO", "capital": "Pachuca"},
        "Jalisco": {"code": "JAL", "capital": "Guadalajara"},
        "Mexico City": {"code": "CDMX", "capital": "Mexico City"},
        "Mexico State": {"code": "MEX", "capital": "Toluca"},
        "Michoacán": {"code": "MIC", "capital": "Morelia"},
        "Morelos": {"code": "MOR", "capital": "Cuernavaca"},
        "Nayarit": {"code": "NAY", "capital": "Tepic"},
        "Nuevo León": {"code": "NL", "capital": "Monterrey"},
        "Oaxaca": {"code": "OAX", "capital": "Oaxaca"},
        "Puebla": {"code": "PUE", "capital": "Puebla"},
        "Querétaro": {"code": "QRO", "capital": "Querétaro"},
        "Quintana Roo": {"code": "ROO", "capital": "Chetumal"},
        "San Luis Potosí": {"code": "SLP", "capital": "San Luis Potosí"},
        "Sinaloa": {"code": "SIN", "capital": "Culiacán"},
        "Sonora": {"code": "SON", "capital": "Hermosillo"},
        "Tabasco": {"code": "TAB", "capital": "Villahermosa"},
        "Tamaulipas": {"code": "TAM", "capital": "Ciudad Victoria"},
        "Tlaxcala": {"code": "TLX", "capital": "Tlaxcala"},
        "Veracruz": {"code": "VER", "capital": "Xalapa"},
        "Yucatán": {"code": "YUC", "capital": "Mérida"},
        "Zacatecas": {"code": "ZAC", "capital": "Zacatecas"},
    },
    
    "Italy": {
        "Abruzzo": {"code": "ABR", "capital": "L'Aquila"},
        "Aosta Valley": {"code": "VDA", "capital": "Aosta"},
        "Apulia": {"code": "PUG", "capital": "Bari"},
        "Basilicata": {"code": "BAS", "capital": "Potenza"},
        "Calabria": {"code": "CAL", "capital": "Catanzaro"},
        "Campania": {"code": "CAM", "capital": "Naples"},
        "Emilia-Romagna": {"code": "EMR", "capital": "Bologna"},
        "Friuli-Venezia Giulia": {"code": "FVG", "capital": "Trieste"},
        "Lazio": {"code": "LAZ", "capital": "Rome"},
        "Liguria": {"code": "LIG", "capital": "Genoa"},
        "Lombardy": {"code": "LOM", "capital": "Milan"},
        "Marche": {"code": "MAR", "capital": "Ancona"},
        "Molise": {"code": "MOL", "capital": "Campobasso"},
        "Piedmont": {"code": "PIE", "capital": "Turin"},
        "Sardinia": {"code": "SAR", "capital": "Cagliari"},
        "Sicily": {"code": "SIC", "capital": "Palermo"},
        "Trentino-Alto Adige": {"code": "TAA", "capital": "Trento"},
        "Tuscany": {"code": "TOS", "capital": "Florence"},
        "Umbria": {"code": "UMB", "capital": "Perugia"},
        "Veneto": {"code": "VEN", "capital": "Venice"},
    },
    
    "Spain": {
        "Andalusia": {"code": "AN", "capital": "Seville"},
        "Aragon": {"code": "AR", "capital": "Zaragoza"},
        "Asturias": {"code": "AS", "capital": "Oviedo"},
        "Balearic Islands": {"code": "IB", "capital": "Palma"},
        "Basque Country": {"code": "PV", "capital": "Vitoria-Gasteiz"},
        "Canary Islands": {"code": "CN", "capital": "Las Palmas"},
        "Cantabria": {"code": "CB", "capital": "Santander"},
        "Castile and León": {"code": "CL", "capital": "Valladolid"},
        "Castilla-La Mancha": {"code": "CM", "capital": "Toledo"},
        "Catalonia": {"code": "CT", "capital": "Barcelona"},
        "Extremadura": {"code": "EX", "capital": "Mérida"},
        "Galicia": {"code": "GA", "capital": "Santiago de Compostela"},
        "La Rioja": {"code": "RI", "capital": "Logroño"},
        "Madrid": {"code": "MD", "capital": "Madrid"},
        "Murcia": {"code": "MC", "capital": "Murcia"},
        "Navarre": {"code": "NC", "capital": "Pamplona"},
        "Valencia": {"code": "VC", "capital": "Valencia"},
    },
    
    "Russia": {
        "Moscow": {"code": "MOW", "capital": "Moscow"},
        "Saint Petersburg": {"code": "SPE", "capital": "Saint Petersburg"},
        "Leningrad Oblast": {"code": "LEN", "capital": "Gatchina"},
        "Moscow Oblast": {"code": "MOS", "capital": "Krasnogorsk"},
        "Krasnodar Krai": {"code": "KDA", "capital": "Krasnodar"},
        "Sverdlovsk Oblast": {"code": "SVE", "capital": "Yekaterinburg"},
        "Rostov Oblast": {"code": "ROS", "capital": "Rostov-on-Don"},
        "Republic of Tatarstan": {"code": "TA", "capital": "Kazan"},
        "Bashkortostan": {"code": "BA", "capital": "Ufa"},
        "Chelyabinsk Oblast": {"code": "CHE", "capital": "Chelyabinsk"},
        "Samara Oblast": {"code": "SAM", "capital": "Samara"},
        "Nizhny Novgorod Oblast": {"code": "NIZ", "capital": "Nizhny Novgorod"},
        "Novosibirsk Oblast": {"code": "NVS", "capital": "Novosibirsk"},
        "Krasnoyarsk Krai": {"code": "KYA", "capital": "Krasnoyarsk"},
        "Perm Krai": {"code": "PER", "capital": "Perm"},
    },
    
    "South Africa": {
        "Eastern Cape": {"code": "EC", "capital": "Bhisho"},
        "Free State": {"code": "FS", "capital": "Bloemfontein"},
        "Gauteng": {"code": "GP", "capital": "Johannesburg"},
        "KwaZulu-Natal": {"code": "KZN", "capital": "Pietermaritzburg"},
        "Limpopo": {"code": "LP", "capital": "Polokwane"},
        "Mpumalanga": {"code": "MP", "capital": "Mbombela"},
        "North West": {"code": "NW", "capital": "Mahikeng"},
        "Northern Cape": {"code": "NC", "capital": "Kimberley"},
        "Western Cape": {"code": "WC", "capital": "Cape Town"},
    },
    
    "Argentina": {
        "Buenos Aires": {"code": "BA", "capital": "La Plata"},
        "Buenos Aires City": {"code": "CABA", "capital": "Buenos Aires"},
        "Catamarca": {"code": "CT", "capital": "San Fernando del Valle de Catamarca"},
        "Chaco": {"code": "CC", "capital": "Resistencia"},
        "Chubut": {"code": "CH", "capital": "Rawson"},
        "Córdoba": {"code": "CB", "capital": "Córdoba"},
        "Corrientes": {"code": "CR", "capital": "Corrientes"},
        "Entre Ríos": {"code": "ER", "capital": "Paraná"},
        "Formosa": {"code": "FO", "capital": "Formosa"},
        "Jujuy": {"code": "JY", "capital": "San Salvador de Jujuy"},
        "La Pampa": {"code": "LP", "capital": "Santa Rosa"},
        "La Rioja": {"code": "LR", "capital": "La Rioja"},
        "Mendoza": {"code": "MZ", "capital": "Mendoza"},
        "Misiones": {"code": "MN", "capital": "Posadas"},
        "Neuquén": {"code": "NQ", "capital": "Neuquén"},
        "Río Negro": {"code": "RN", "capital": "Viedma"},
        "Salta": {"code": "SA", "capital": "Salta"},
        "San Juan": {"code": "SJ", "capital": "San Juan"},
        "San Luis": {"code": "SL", "capital": "San Luis"},
        "Santa Cruz": {"code": "SC", "capital": "Río Gallegos"},
        "Santa Fe": {"code": "SF", "capital": "Santa Fe"},
        "Santiago del Estero": {"code": "SE", "capital": "Santiago del Estero"},
        "Tierra del Fuego": {"code": "TF", "capital": "Ushuaia"},
        "Tucumán": {"code": "TM", "capital": "San Miguel de Tucumán"},
    },
    
    "South Korea": {
        "Seoul": {"code": "11", "capital": "Seoul"},
        "Busan": {"code": "26", "capital": "Busan"},
        "Daegu": {"code": "27", "capital": "Daegu"},
        "Incheon": {"code": "28", "capital": "Incheon"},
        "Gwangju": {"code": "29", "capital": "Gwangju"},
        "Daejeon": {"code": "30", "capital": "Daejeon"},
        "Ulsan": {"code": "31", "capital": "Ulsan"},
        "Sejong": {"code": "36", "capital": "Sejong"},
        "Gyeonggi": {"code": "41", "capital": "Suwon"},
        "Gangwon": {"code": "42", "capital": "Chuncheon"},
        "North Chungcheong": {"code": "43", "capital": "Cheongju"},
        "South Chungcheong": {"code": "44", "capital": "Hongseong"},
        "North Jeolla": {"code": "45", "capital": "Jeonju"},
        "South Jeolla": {"code": "46", "capital": "Muan"},
        "North Gyeongsang": {"code": "47", "capital": "Andong"},
        "South Gyeongsang": {"code": "48", "capital": "Changwon"},
        "Jeju": {"code": "49", "capital": "Jeju City"},
    },
}


# Helper functions
def get_all_countries() -> list[str]:
    """Return list of all country names."""
    return list(COUNTRIES.keys())


def get_country_info(country_name: str) -> dict | None:
    """Get info for a country."""
    return COUNTRIES.get(country_name)


def get_regions_for_country(country_name: str) -> dict:
    """Get all regions (states/provinces) for a country."""
    return REGIONS.get(country_name, {})


def get_region_names(country_name: str) -> list[str]:
    """Get list of region names for a country."""
    return list(REGIONS.get(country_name, {}).keys())


def is_valid_country(country_name: str) -> bool:
    """Check if a country name is valid."""
    return country_name in COUNTRIES


def is_valid_region(country_name: str, region_name: str) -> bool:
    """Check if a region name is valid for a country."""
    country_regions = REGIONS.get(country_name, {})
    return region_name in country_regions


def has_regions(country_name: str) -> bool:
    """Check if a country has regions data available."""
    return country_name in REGIONS and len(REGIONS[country_name]) > 0


def get_country_for_region(region_name: str) -> str | None:
    """Find which country a region belongs to (searches all countries)."""
    for country, regions in REGIONS.items():
        if region_name in regions:
            return country
    return None
